import { Navigate, Route, Routes, useParams, useLocation } from "react-router-dom";
import { useState, useEffect } from "react";
import axios from "axios";
import { findQuizById } from "../../client";
import "./index.css";
import { get } from "http";
import { Quiz } from "../../types/types";

// This is quiz Preview screen generated by copliot for now
function QuizPreview() {
    const { courseId, quizId } = useParams();
    const [quiz, setQuiz] = useState<any[]>([]);

    //need to add courseID to parameter later.
    const getQuizByQuizId = async () => {
        const response = await findQuizById(quizId);
        console.log(response);
        setQuiz([response]);
    };

    useEffect(() => { getQuizByQuizId(); }, []);
    return (
        <div className="quiz-preview">
            <h1>Quiz Preview</h1>
            <div>
                {quiz.map((quiz: Quiz) => (
                    <div key={quiz._id}>
                        <h2>{quiz.title}</h2>
                        <p>{quiz.description}</p>
                        <p>{quiz.points} points</p>
                        <p>Time limit: {quiz.timeLimit} minutes</p>
                        <p>Due: {quiz.dueDate}</p>
                    </div>
                ))}
            </div>
        </div>
    );
}
export default QuizPreview;